import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"]
})

const clashdisplay = localFont({
  src: './ClashDisplay-Medium.otf',
  variable: '--font-clashdisplay'
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} ${geistSans.variable} ${clashdisplay.variable} ${geistMono.variable} antialiased bg-[#82A3A1]`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
